# _______  _____  __   _ _______ _____  ______
# |       |     | | \  | |______   |   |  ____
# |_____  |_____| |  \_| |       __|__ |_____|

debug: false

modules:
  betterBeds: true

preferences:
  betterBeds:
    # If there's only one player, the server will also instantly go to the next day. If false, beds will be vanilla style.
    changeIfAlone: true
    # The percentage of players needed to pass the day.
    percentageNeeded: 25
    # Changes the maximum value to enter a bed, if longer than 3 (for X and Z) and 2 (for Y), Minecraft will limit your enter automatically.
    maximumXZDistanceToSleep: 3
    maximumYDistanceToSleep: 2

permissions:
  reload: bu.reload
