###########################
  # BedUtils by JasperEdits #
  ###########################

  modules:
    betterSleep:
      enabled: true
      playerPercentage: 25 # Percentage of people needed to get to the next day.
      messages: # Set to "0" to disable message.
        lonelyPlayer: "&8[&aInfo&8] &aYou are alone, sleeping won't be modified."
        moreNeeded: "&8[&aInfo&8] &e%sleeping% &aof &e%connected% &asleeping. &8(%sleepingPercent%, &e%percentNeeded% needed&8)"
        success: "&8[&aInfo&8] &aDay passed."
        youCantSleepNow: "&8[&cError&8] &cYou can't sleep yet"

  enableMessage: "&aBedUtils enabled."
  disableMessage: "&cBedUtils disabled."