name: BedUtils
version: 2.1
main: me.jasperedits.bedutils.BedUtilsPlugin
api-version: 1.16
authors: [ JasperEdits ]
description: A simple plugin that modifies beds for multiplayer purposes.

commands:
  bed:
    aliases: [cama, camas, dormir]